Jedi = ["Aayla Secura", "Adi Gallia", "Agen Kolar", "Anakin Skywalker", "Barris Offee", "Bultar Swan", "Cin Drallig", "Coleman Trebor", "Depa Billaba", "Eeth Koth", "Even Piell", "Jocasta Nu", "Ki-Adi Mundi", "Kit Fisto", "Luke Skywalker", "Luminara Unduli", "Mace Windu", "Obi-Wan Kenobi", "Oppo Ranchis", "Plo Koon", "Qui-Gon Jinn", "Saesee Tiin", "Shaak Ti", "Stass Allie", "Yaddle", "Yareal Poof", "Yoda", "Zett Jukassa"]


print(Jedi[1])
print(Jedi[2])
print(Jedi[3])
print(Jedi[4])
print(Jedi[5])
print(Jedi[6])
print(Jedi[7])
print(Jedi[8])
print(Jedi[9])
print(Jedi[10])
print(Jedi[11])
print(Jedi[12])
print(Jedi[13])
print(Jedi[14])
print(Jedi[15])
print(Jedi[16])
print(Jedi[17])
print(Jedi[18])
print(Jedi[19])
print(Jedi[20])
print(Jedi[21])
print(Jedi[22])
print(Jedi[23])
print(Jedi[24])
print(Jedi[25])
print(Jedi[26])
print(Jedi[27])
print(Jedi[28])


Jedi.remove(1)